### PR TITLE
Adding dockerfile

### PR DESCRIPTION
**Pull request by mmirecki**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@mmirecki  thanks for the PR!
Is this to add a Dockerfile for auto build of OCP image? From the proposed dockerfile, it doesn't look like so. If we were to add a general dockerfile, it might be good to send a PR in intel repo (which is upstream) and then we can backport?

**Comment by mmirecki** [comment]
The dockerfile is to be used for a container that copies the cni binary to a node, as part of the sriov operator. It's only task would be to copy the cni binary, nothing else.

**Comment by zshi-redhat** [comment]
> The dockerfile is to be used for a container that copies the cni binary to a node, as part of the sriov operator. It's only task would be to copy the cni binary, nothing else.

Yes, the image will only be used to copy bond cni binary to nodes. I was trying to understand if this is a openshift specific dockerfile which may need different base image.

**Comment by mmirecki** [comment]
The plan is to use it with the sriov operator, which is openshift specific. 
Use ubi?

**Comment by zshi-redhat** [comment]
> The plan is to use it with the sriov operator, which is openshift specific.

Do we want to use intel/bond-cni as upstream repo or build our own bond-cni from scratch?

> Use ubi?

Here is an example of multus image building: https://github.com/openshift/multus-cni/blob/master/Dockerfile.openshift
Several changes may be needed:
1) add suffix to dockerfile to distinguish from upstream dockerfile
2) use base image from openhift
3) add openshift Labels

**Comment by mmirecki** [comment]
> > The plan is to use it with the sriov operator, which is openshift specific.
> 
> Do we want to use intel/bond-cni as upstream repo or build our own bond-cni from scratch?
Use  intel/bond-cni
I see you already started here: https://github.com/openshift/bond-cni/pull/1

**Comment by mmirecki** [comment]
> 1. add suffix to dockerfile to distinguish from upstream dockerfile
> 2. use base image from openhift
> 3. add openshift Labels
Done

**Pull request merged**
